### ISSUE TITLE
Error encountered when processDirs is unable to find the right level to create objects.

### ISSUE THREAD

**Issue by shihchengyen** [grero/DataProcessingTools#54]
E.g. Spiketrain object is defined to be a cell object, but when there are no cell directories present in the channel directory, we get this error:
st = DPT.objects.processDirs(None, pyh.Spiketrain)
Traceback (most recent call last):

  File "<ipython-input-23-3b438dd0868c>", line 1, in <module>
    st = DPT.objects.processDirs(None, pyh.Spiketrain)

  File "/Volumes/User/shihcheng/Dropbox/Work/Python/DataProcessingTools/DataProcessingTools/objects.py", line 257, in processDirs
    return obj

UnboundLocalError: local variable 'obj' referenced before assignment

**Comment by grero** [comment]
Can you check if #55 fixes the issue?

**Comment by shihchengyen** [comment]
Yes, it works! Thanks!
